name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: mcr.microsoft.com/dotnet/runtime:8.0-nanoserver-1809

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ***REMOVED***

    - name: Push the Docker image
      run: docker image push ***REMOVED***
